### ISSUE TITLE
Identity for flintlock hosts, clients and microVMs

### ISSUE THREAD

**Issue by richardcase** [liquidmetal-dev/flintlock#7]
Flintlock offers three authentication postures — none, a static shared token,
and mTLS — and **all three discard who is calling**. This epic tracks the work
to give flintlock hosts, clients and microVMs real identities.

## The problem

Authentication today is a pure gate: it either lets an RPC through or rejects
it. Nothing downstream ever learns *who* called.

- `pkg/auth/basic.go:37-38` writes `Authenticated` and `AuthMethod` into the
  request context. **Nothing in the repository ever reads them** — the only
  reference outside `pkg/auth/` is a single import in
  `internal/command/run/run.go`. Dead scaffolding.
- `pkg/auth/tls.go:43-45` sets `tls.RequireAndVerifyClientCert`, proving the
  peer certificate chains to the configured CA — then discards the
  certificate. There is no `peer.FromContext`, `credentials.TLSInfo` or
  `VerifiedChains` call anywhere in the tree.
- So `hack/scripts/gen_local_certs.sh` issues client certs with
  `CN="Liquid Metal Client 1"`, and that CN has no runtime meaning at all.

What follows from that:

- **Any** holder of **any** CA-issued certificate can get, list and delete
  **any** microVM in **any** namespace. `namespace` is caller-supplied and
  unconstrained (`infrastructure/grpc/server.go:158-166`).
- `MicroVMExec` and `MicroVMSSHProxy` — shell-level access into guests — sit
  behind the identical single global gate as a read-only `ServerInfo` call.
- `MicroVMSpec` records `CreatedAt`, `UpdatedAt`, `DeletedAt` and **no
  creator**.
- `MicroVMSpec.labels` is accepted on the wire and silently dropped
  (`infrastructure/grpc/convert.go:32` and `:173`).
- `LoadTLSForGRPC` loads the keypair **once at process start**, so flintlockd
  cannot pick up a renewed certificate without a restart.
- Enabling `--enable-http` **unauthenticates the API** — the gateway dials its
  own gRPC server with `insecure.NewCredentials()` and injects no token.

## Why SPIFFE

Adopt SPIFFE as the identity **vocabulary**; make SPIRE an optional **source**.

The flintlock-specific argument: flintlockd is dialed by IP on bare metal (the
documented usage is `hammertime create -a 192.168.1.66:9090`). Conventional TLS
identity is hostname verification, a poor fit for re-imaged hosts on DHCP.
SPIFFE deliberately decouples identity from network location.

What it buys:

1. **Naming** — `spiffe://<trust-domain>/...` carried in the certificate's URI
   SAN. That field is already inside the certificate flintlock already
   verifies, so extracting it is a few lines, not a subsystem.
2. **Mutual host identity** — the client matches the server's SPIFFE ID rather
   than a DNS name.
3. **A rotation interface** — needed regardless, given the load-once bug above.
4. **Guest identity over a delivery path that already exists** —
   `MicroVMSpec.metadata` to MMDS (Firecracker) or the cloud-init drive (Cloud
   Hypervisor), with `addInstanceData` in `core/application/commands.go` as
   precedent for flintlock injecting its own values.
5. **`VMID` is already a SPIFFE-shaped name** — `core/models/vmid.go` is
   `{name, namespace, uid}`.

What it does **not** buy, stated plainly: SPIFFE's real security value is
SPIRE's *attestation*. Without SPIRE, trust still reduces to "whoever holds the
key file". That is no worse than today's mTLS, and it lets flintlock slot into
a SPIRE deployment later with no API change — but it is not attestation.
SPIFFE also provides no authorization; SPIFFE IDs are names.

## Proposed naming scheme

```
spiffe://<trust-domain>/flintlock/host/<host-id>
spiffe://<trust-domain>/flintlock/client/<name>
spiffe://<trust-domain>/flintlock/microvm/<namespace>/<name>
```

To be ratified by the ADR.

## Direction agreed so far

- SPIFFE-compatible, **SPIRE optional**: use the Workload API if a socket is
  configured, otherwise fall back to credentials on disk.
- Authorization delegates to an **external policy engine** (OPA or Cedar)
  behind a `ports.Authorizer` seam, rather than a bespoke policy language.
- `--basic-auth-token` is **deprecated, not removed** — it keeps working, logs
  a deprecation warning, and yields a distinct low-privilege principal so
  existing deployments and the Cluster API provider do not break.

## Work

The ADR comes first and blocks the implementation issues. #1231 is the
foundational primitive that most of the rest depends on.

- [ ] #1230 — ADR: identity model for flintlock hosts, clients and microVMs
- [ ] #1231 — Extract caller identity from the connection into a request principal
- [ ] #1232 — Record the creating principal on a microVM (and implement labels)
- [ ] #1233 — Authorize requests by principal via a pluggable policy engine
- [ ] #1234 — Client-side identity: verify the server's SPIFFE ID and add client auth helpers
- [ ] #1235 — Hot-reload credentials and support the SPIFFE Workload API as a source
- [ ] #1236 — Issue SPIFFE SVIDs to guest microVMs via the metadata path
- [ ] #1237 — HTTP gateway bypasses TLS and authentication
- [ ] #1238 — Authentication hardening: constant-time token compare, unenforced client CA, unconditional reflection
- [ ] #1239 — Document TLS, mTLS and identity configuration

- [ ] #1240 — Update downstream clients (battery, brigade, fl, hammertime) for the identity model

**Comment by richardcase** [comment]
The original checklist above is now answered by the rewritten issue body and the child issues:

- *API standards* — out of scope for this epic; tracked separately.
- *Which auth mechanism is needed (token, cert)* — both, plus the missing third thing: identity. The direction is SPIFFE as the identity vocabulary with SPIRE optional, and `--basic-auth-token` deprecated rather than removed. See #1230.
- *Is it ok to ignore auth to start with* — answered by four and a half years of running without it. The concrete consequences are listed in the body.
- *ADR / Proposal* — #1230.

Labelled `lifecycle/frozen` so the stale bot stops closing this.

**Comment by phoban01** [comment]
Makes sense from my point of view, stable identities make multi-host provisioning story much better.

Being able to write authorization policies against the MicroVMExec and SSH endpoints would solve a real problem too; this is something I've encountered working on https://github.com/phoban01/flintlock-runner and had to solve in a layer above flintlock. For multi-tenant setups it's going to be essential.
